import os
import json
import uuid
import datetime
from typing import Optional, List, Dict, Any, Tuple
from pathlib import Path
from dotenv import load_dotenv

from backend import database as db
from backend.gemini_service import (
    detect_language_simple,
    transcribe_audio_file,
    LANGUAGE_NAMES
)
from backend.schemas import (
    ChatRequest,
    ChatResponse,
    ChatSource
)

load_dotenv()

# System prompt adhering strictly to Part AS & Chatbot System Instruction
SYSTEM_INSTRUCTION = """
You are RAKA AI Assistant, the official civic intelligence companion for India's RAKA Domain AI platform.
You help citizens, civic engineers, and hackathon judges understand the information generated by RAKA.

CRITICAL INSTRUCTIONS:
1. Use ONLY verified RAKA context supplied to you below.
2. Never invent facts, budgets, funding, official government approvals, or deadlines.
3. Never claim a problem is resolved unless the database explicitly says so.
4. Clearly distinguish:
   - Citizen-reported information (from typed statement or spoken voice)
   - Image-observed evidence (from photographic analysis)
   - AI classification (category, sub-category, engineering disciplines)
   - Cluster-supported facts (correlated citizen complaints)
   - Inferred insights (safety risks, potential action areas)
5. Answer in the user's selected or detected language (English, Hindi, Marathi, etc.).
6. Use simple, reassuring, and professional language for citizens.
7. Do not expose private citizen PII or exact raw GPS coordinates. Use generalized locations.
8. Do not reveal hidden chain-of-thought or internal reasoning scratchpads.
9. RAKA is an AI assistant for understanding problem intelligence, not an authority making official government decisions.

OUTPUT FORMAT:
Return a JSON object with:
{
  "message": "Your helpful response here in the requested language",
  "sources": [
    {"type": "AI_ANALYSIS", "field": "category", "snippet": "Roads & Transport classification"},
    {"type": "CLUSTER", "field": "related_reports", "snippet": "3 related citizen reports in cluster"}
  ],
  "relatedActions": ["Explain My Analysis", "Show Related Problems", "What Happens Next?"]
}
"""


def gather_chat_context(
    problem_id: Optional[str] = None,
    cluster_id: Optional[str] = None,
    challenge_id: Optional[str] = None,
    solution_id: Optional[str] = None,
    collaboration_id: Optional[str] = None,
    role: Optional[str] = "CITIZEN"
) -> Tuple[str, Dict[str, Any], List[ChatSource]]:
    """
    Gathers real verified data from the RAKA database based on active context.
    Returns: (context_type, context_dict, available_sources)
    """
    context_type = "GENERAL"
    ctx: Dict[str, Any] = {}
    sources: List[ChatSource] = []

    conn = db.get_connection()
    c = conn.cursor()


    # 0. Collaboration Workspace Context
    if collaboration_id:
        context_type = "COLLABORATION"
        collab = db.get_collaboration(collaboration_id)
        if collab:
            ctx["collaboration"] = collab
            sources.append(ChatSource(type="COLLABORATION", field="partners", snippet=f"{collab.get('university_name')} + {collab.get('company_name')}"))
            sources.append(ChatSource(type="COLLABORATION", field="progress", snippet=f"{collab.get('progress_percentage')}% ({collab.get('current_milestone')})"))
            if collab.get("challenge_id"):
                challenge_id = collab.get("challenge_id")
            if collab.get("solution_id"):
                solution_id = collab.get("solution_id")

    # 0.1 Solution Context
    if solution_id:
        if context_type == "GENERAL":
            context_type = "SOLUTION"
        sol = db.get_solution(solution_id)
        if sol:
            ctx["solution"] = sol
            sources.append(ChatSource(type="SOLUTION", field="title", snippet=sol.get("title")))
            sources.append(ChatSource(type="SOLUTION", field="proposer", snippet=sol.get("proposer_name")))
            if sol.get("challenge_id") and not challenge_id:
                challenge_id = sol.get("challenge_id")

    # 1. Challenge Context (Highest priority if present)
    if challenge_id:
        context_type = "CHALLENGE"
        ch = db.get_challenge(challenge_id)
        if ch:
            ctx["challenge"] = ch
            sources.append(ChatSource(type="CHALLENGE", field="title", snippet=ch.get("title")))
            sources.append(ChatSource(type="CHALLENGE", field="status", snippet=ch.get("challenge_status")))
            sources.append(ChatSource(type="CHALLENGE", field="readiness", snippet=f"Score: {ch.get('readiness_score')}"))
            
            # Fetch evidence
            ev_list = db.get_challenge_evidence(challenge_id)
            ctx["challenge_evidence"] = ev_list
            if ch.get("cluster_id"):
                cluster_id = ch.get("cluster_id")

    # 2. Cluster Context
    if cluster_id:
        if context_type == "GENERAL":
            context_type = "CLUSTER"
        if db.USE_POSTGRES:
            c.execute("SELECT * FROM problem_clusters WHERE id = %s", (cluster_id,))
            cl_row = c.fetchone()
        else:
            c.execute("SELECT * FROM problem_clusters WHERE id = ?", (cluster_id,))
            cl_row = c.fetchone()

        if cl_row:
            ctx["cluster"] = {
                "id": str(cl_row["id"]),
                "title": cl_row["cluster_title"],
                "category": cl_row["category"],
                "problem_count": cl_row["problem_count"],
                "status": cl_row["status"]
            }
            sources.append(ChatSource(type="CLUSTER", field="cluster_title", snippet=cl_row["cluster_title"]))
            sources.append(ChatSource(type="CLUSTER", field="problem_count", snippet=f"{cl_row['problem_count']} member reports"))

        # Fetch cluster members
        if db.USE_POSTGRES:
            c.execute("""
                SELECT p.id, p.problem_text, p.city, p.locality, a.category, a.sub_category, a.problem_summary
                FROM problem_cluster_members m
                JOIN problems p ON p.id = m.problem_id
                LEFT JOIN problem_ai_analysis a ON a.problem_id = p.id
                WHERE m.cluster_id = %s LIMIT 5;
            """, (cluster_id,))
            m_rows = c.fetchall()
        else:
            c.execute("""
                SELECT p.id, p.problem_text, p.city, p.locality, a.category, a.sub_category, a.problem_summary
                FROM problem_cluster_members m
                JOIN problems p ON p.id = m.problem_id
                LEFT JOIN problem_ai_analysis a ON a.problem_id = p.id
                WHERE m.cluster_id = ? LIMIT 5;
            """, (cluster_id,))
            m_rows = c.fetchall()

        ctx["cluster_members"] = [
            {
                "summary": r["problem_summary"] if db.USE_POSTGRES else r[6],
                "category": r["category"] if db.USE_POSTGRES else r[4],
                "sub_category": r["sub_category"] if db.USE_POSTGRES else r[5],
                "area": (r["locality"] if db.USE_POSTGRES else r[3]) or (r["city"] if db.USE_POSTGRES else r[2]) or "Local Area"
            }
            for r in m_rows
        ]

    # 3. Problem Context
    if problem_id:
        if context_type == "GENERAL":
            context_type = "PROBLEM"
        if db.USE_POSTGRES:
            c.execute("SELECT * FROM problems WHERE id = %s", (problem_id,))
            p_row = c.fetchone()
        else:
            c.execute("SELECT * FROM problems WHERE id = ?", (problem_id,))
            p_row = c.fetchone()

        if p_row:
            gen_loc = (p_row["locality"] if db.USE_POSTGRES else p_row[19]) or (p_row["city"] if db.USE_POSTGRES else p_row[16]) or "Local Area"
            ctx["problem"] = {
                "id": str(p_row["id"]),
                "problem_text": p_row["problem_text"] if db.USE_POSTGRES else p_row[2],
                "has_location": bool(p_row["has_location"] if db.USE_POSTGRES else p_row[4]),
                "locality": gen_loc,
                "city": p_row["city"] if db.USE_POSTGRES else p_row[16],
                "has_image": bool(p_row["image_url"] if db.USE_POSTGRES else p_row[3]),
                "voice_transcript": p_row["voice_transcript"] if db.USE_POSTGRES else p_row[14],
                "detected_language": p_row["detected_language"] if db.USE_POSTGRES else p_row[15]
            }
            sources.append(ChatSource(type="CITIZEN_REPORT", field="problem_text", snippet=(p_row["problem_text"] if db.USE_POSTGRES else p_row[2])[:80]))
            if p_row["voice_transcript"] if db.USE_POSTGRES else p_row[14]:
                sources.append(ChatSource(type="VOICE_TRANSCRIPT", field="voice_transcript", snippet=(p_row["voice_transcript"] if db.USE_POSTGRES else p_row[14])[:60]))

        # Load AI Analysis
        if db.USE_POSTGRES:
            c.execute("SELECT * FROM problem_ai_analysis WHERE problem_id = %s", (problem_id,))
            a_row = c.fetchone()
        else:
            c.execute("SELECT * FROM problem_ai_analysis WHERE problem_id = ?", (problem_id,))
            a_row = c.fetchone()

        if a_row:
            cat = a_row["category"] if db.USE_POSTGRES else a_row[2]
            sub = a_row["sub_category"] if db.USE_POSTGRES else a_row[19]
            summary = a_row["problem_summary"] if db.USE_POSTGRES else a_row[3]
            ctx["analysis"] = {
                "category": cat,
                "sub_category": sub,
                "problem_summary": summary,
                "urgency": a_row["urgency"] if db.USE_POSTGRES else a_row[4],
                "complexity": a_row["complexity"] if db.USE_POSTGRES else a_row[5],
                "technical_discipline": a_row["technical_discipline"] if db.USE_POSTGRES else a_row[6],
                "impact_areas": a_row["impact_areas"] if db.USE_POSTGRES else a_row[12],
                "image_observations": a_row["image_observations"] if db.USE_POSTGRES else a_row[14]
            }
            sources.append(ChatSource(type="AI_ANALYSIS", field="category", snippet=f"{cat} ({sub})"))
            sources.append(ChatSource(type="AI_ANALYSIS", field="problem_summary", snippet=summary[:80] if summary else ""))

        # Load Step 4 Recommendations
        s4_recs = db.get_step4_recommendations(problem_id)
        if s4_recs:
            ctx["step4"] = s4_recs
            top_s = s4_recs.get("stakeholders", [])
            if top_s:
                sources.append(ChatSource(type="STAKEHOLDER", field="name", snippet=top_s[0].get("name")))

    conn.close()
    return context_type, ctx, sources


def heuristic_chat_response(
    message: str,
    context_type: str,
    context: Dict[str, Any],
    lang: str,
    sources: List[ChatSource]
) -> ChatResponse:
    """
    Dynamic contextual response engine for when Gemini API is offline.
    Uses real database records to answer questions in English, Hindi, or Marathi.
    """
    msg_lower = message.strip().lower()
    resp_text = ""
    related_actions = []

    # Extract available context fields
    prob = context.get("problem", {})
    analysis = context.get("analysis", {})
    cluster = context.get("cluster", {})
    challenge = context.get("challenge", {})
    step4 = context.get("step4", {})

    category = analysis.get("category") or challenge.get("category") or "General Civic Issue"
    sub_cat = analysis.get("sub_category") or challenge.get("sub_category") or ""
    summary = analysis.get("problem_summary") or challenge.get("problem_statement") or prob.get("problem_text") or ""
    locality = prob.get("locality") or challenge.get("generalized_location") or "your area"
    transcript = prob.get("voice_transcript") or ""
    img_obs = analysis.get("image_observations") or []
    if isinstance(img_obs, str):
        try:
            img_obs = json.loads(img_obs)
        except Exception:
            img_obs = [img_obs]

    stk_list = step4.get("stakeholders", []) or challenge.get("stakeholder_types", [])
    stk_name = stk_list[0].get("name") if (stk_list and isinstance(stk_list[0], dict)) else (stk_list[0] if stk_list else "Local Civic Body")

    # Question Intents
    is_hindi = lang in ["hi", "Hindi", "Hindi (हिन्दी)"] or any(ch in message for ch in ["क्या", "कैसे", "कौन", "समस्या", "चुनौती", "तस्वीर"])
    is_marathi = lang in ["mr", "Marathi", "Marathi (मराठी)"] or any(ch in message for ch in ["काय", "कसे", "कोण", "समस्या", "आहे"])


    # University / Student Project Questions
    if any(k in msg_lower for k in ["university", "student project", "research", "contribute", "final year", "छात्र", "शोध", "योगदान"]):
        if is_hindi:
            resp_text = f"विश्वविद्यालय और इंजीनियरिंग कॉलेज इस चुनौती ({category}) पर शोध प्रस्ताव, बी.टेक/एम.टेक फाइनल-ईयर प्रोजेक्ट, या लैब प्रोटोटाइप प्रस्तुत कर सकते हैं। आप 'Propose a Solution' बटन पर क्लिक करके अपने विभाग और कार्यप्रणाली का विवरण दे सकते हैं।"
        else:
            resp_text = f"Universities can adopt this '{category}' challenge as an active Faculty Research Study, Final-Year B.Tech/M.Tech Capstone Project, or Field Pilot. You can submit a structured methodology under 'Propose a Solution' to unlock startup prototyping and municipal telemetry collaboration."
        related_actions = ["Propose a Solution", "Submit Student Project", "Explore Challenges"]
        return ChatResponse(
            message=resp_text,
            language="hi" if is_hindi else ("mr" if is_marathi else "en"),
            conversationId=str(uuid.uuid4()),
            contextType=context_type,
            sources=sources,
            relatedActions=related_actions
        )

    # Industry / Startup Collaboration Questions
    if any(k in msg_lower for k in ["startup", "industry", "collaborate", "company", "pilot", "commercial", "स्टार्टअप", "सहयोग"]):
        if is_hindi:
            resp_text = f"स्टार्टअप्स और उद्योग भागीदार विश्वविद्यालय द्वारा प्रस्तावित समाधानों के साथ 'Connect with University' के माध्यम से जुड़ सकते हैं। आप फील्ड परीक्षण, सामग्री आपूर्ति, या हार्डवेयर प्रोटोटाइप में सहयोग कर सकते हैं।"
        else:
            resp_text = f"Startups & Industry partners can discover verified University research solutions for this '{category}' challenge, and submit a 'Connect with University' request to co-develop field prototypes, provide IoT telemetry hardware, or deploy municipal pilots."
        related_actions = ["Connect with University", "View Active Collaborations", "Explore Solutions"]
        return ChatResponse(
            message=resp_text,
            language="hi" if is_hindi else ("mr" if is_marathi else "en"),
            conversationId=str(uuid.uuid4()),
            contextType=context_type,
            sources=sources,
            relatedActions=related_actions
        )

    # Collaboration Workspace Progress Questions
    if any(k in msg_lower for k in ["collaboration", "workspace", "progress", "milestone", "tasks", "प्रगति", "कार्य"]):
        collab = context.get("collaboration", {})
        if collab:
            pct = collab.get("progress_percentage", 15)
            ms = collab.get("current_milestone", "Field Pilot Preparation")
            u_name = collab.get("university_name", "University Team")
            c_name = collab.get("company_name", "Industry Partner")
            if is_hindi:
                resp_text = f"यह सहयोग {u_name} और {c_name} के बीच सक्रिय है। वर्तमान प्रगति: {pct}%। वर्तमान चरण: '{ms}'।"
            else:
                resp_text = f"This active collaboration unites {u_name} with {c_name}. Current progress is at {pct}%, advancing milestone: '{ms}'. Team tasks and verified deliverables are tracked directly in the Collaboration Workspace."
            related_actions = ["Open Collaboration Workspace", "View Task Board", "Add Milestone Update"]
            return ChatResponse(
                message=resp_text,
                language="hi" if is_hindi else ("mr" if is_marathi else "en"),
                conversationId=str(uuid.uuid4()),
                contextType=context_type,
                sources=sources,
                relatedActions=related_actions
            )

    # 1. "What did RAKA understand?" / "मेरी समस्या क्या है?"
    if any(k in msg_lower for k in ["understand", "what is my problem", "summary", "explain", "समस्या क्या", "समस्या काय"]):
        if is_hindi:
            resp_text = f"आपकी रिपोर्ट के अनुसार मुख्य समस्या {locality} में {sub_cat or category} से संबंधित है। RAKA ने विश्लेषण किया: \"{summary[:140]}...\"।"
        elif is_marathi:
            resp_text = f"तुमच्या तक्रारीनुसार मुख्य समस्या {locality} मधील {sub_cat or category} संबंधी आहे. RAKA चे विश्लेषण: \"{summary[:140]}...\"."
        else:
            resp_text = f"According to your report, the primary issue relates to {sub_cat or category} in {locality}. RAKA summarized: \"{summary[:140]}...\"."
        related_actions = ["Show Related Problems", "Explain Stakeholder Match", "What Happens Next?"]

    # 2. "Why classified this way?" / "यह किस category में है?"
    elif any(k in msg_lower for k in ["category", "classified", "why this", "वर्गीकरण", "श्रेणी"]):
        if is_hindi:
            resp_text = f"RAKA ने इसे '{category}' श्रेणी में रखा है और '{sub_cat}' के रूप में पहचाना है। यह निर्णय आपके विवरण और उपलब्ध साक्ष्यों (image/voice) के आधार पर लिया गया है।"
        elif is_marathi:
            resp_text = f"RAKA ने याला '{category}' श्रेणीत आणि '{sub_cat}' उपश्रेणीत वर्गीकृत केले आहे. हे वर्गीकरण आपल्या वर्णनावर आणि पुराव्यावर आधारित आहे."
        else:
            resp_text = f"RAKA classified this report under '{category}' ({sub_cat}). This classification is directly grounded in your description and corroborating evidence."
        related_actions = ["Explain My Analysis", "What Happens Next?"]

    # 3. "What did you see in the image?" / "तस्वीर में क्या देखा?"
    elif any(k in msg_lower for k in ["image", "photo", "see", "तस्वीर", "फोटो", "दिखाई"]):
        obs_text = img_obs[0] if img_obs else "physical defect corresponding to your report"
        if is_hindi:
            resp_text = f"अपलोड की गई तस्वीर के विश्लेषण के आधार पर RAKA ने देखा: {obs_text}। यह भौतिक साक्ष्य समस्या की पुष्टि करता है।"
        elif is_marathi:
            resp_text = f"अपलोड केलेल्या फोटोच्या विश्लेषणावरून RAKA ने पाहिले: {obs_text}. हा पुरावा समस्येची खात्री करतो."
        else:
            resp_text = f"Based on visual analysis of the uploaded photograph, RAKA identified: {obs_text}. This provides physical visual evidence of the condition."
        related_actions = ["Explain My Analysis", "Show Related Problems"]

    # 4. "What did I say?" / "मैंने क्या बोला?"
    elif any(k in msg_lower for k in ["say", "voice", "transcript", "बोला", "कहा"]):
        if transcript:
            if is_hindi:
                resp_text = f"आपकी आवाज़ की रिकॉर्डिंग का ट्रांसक्रिप्ट है: \"{transcript}\"।"
            else:
                resp_text = f"Your recorded voice testimony was transcribed as: \"{transcript}\"."
        else:
            if is_hindi:
                resp_text = "इस रिपोर्ट के साथ कोई ऑडियो रिकॉर्डिंग नहीं जुड़ी थी; लिखित विवरण का उपयोग किया गया।"
            else:
                resp_text = "No audio recording was attached to this report; text description was used."
        related_actions = ["Explain My Analysis"]

    # 5. "Are there similar problems?" / "क्या ऐसी और समस्याएं हैं?"
    elif any(k in msg_lower for k in ["similar", "duplicate", "related", "cluster", "और समस्याएं", "संबंधित"]):
        p_count = cluster.get("problem_count", 1)
        if p_count > 1:
            if is_hindi:
                resp_text = f"जी हाँ, RAKA को आपके क्षेत्र ({locality}) में {p_count} संबंधित रिपोर्ट मिली हैं, जिन्हें एक समस्या समूह (Cluster) में जोड़ा गया है।"
            elif is_marathi:
                resp_text = f"होय, RAKA ला तुमच्या परिसरात {p_count} संबंधित तक्रारी आढळल्या आहेत आणि त्यांचा एक Cluster तयार करण्यात आला आहे."
            else:
                resp_text = f"Yes, RAKA identified {p_count} correlated citizen reports in {locality} describing similar conditions, linked into an active Problem Cluster."
        else:
            if is_hindi:
                resp_text = "वर्तमान डेटा में इस स्थान पर कोई अन्य अत्यधिक समान रिपोर्ट नहीं मिली है। इसे व्यक्तिगत रूप से ट्रैक किया जा रहा है।"
            else:
                resp_text = "RAKA did not find other strongly related reports in the immediate vicinity yet; this report is evaluated individually."
        related_actions = ["Explain Challenge", "What Happens Next?"]

    # 6. "Who can help solve this?" / "कौन मदद कर सकता है?"
    elif any(k in msg_lower for k in ["who", "help", "stakeholder", "department", "कौन", "मदद", "विभाग"]):
        if is_hindi:
            resp_text = f"RAKA ने संभावित सहायक हितधारकों (Stakeholder Types) के रूप में {stk_name} और संबंधित तकनीकी संस्थानों की पहचान की है। यह केवल AI-सहायित सिफ़ारिश है, कोई आधिकारिक आदेश नहीं।"
        elif is_marathi:
            resp_text = f"RAKA ने संभाव्य मदतनीस म्हणून {stk_name} आणि संबंधित तांत्रिक संस्थांची शिफारस केली आहे. ही केवळ AI-आधारित शिफारस आहे."
        else:
            resp_text = f"RAKA identified potentially relevant stakeholder types including {stk_name} and technical engineering partners. These are AI-assisted routing recommendations, not official assignments."
        related_actions = ["Explain Stakeholder Match", "What Happens Next?"]

    # 7. "Why was this challenge created?" / "यह चुनौती क्यों बनाई गई?"
    elif any(k in msg_lower for k in ["challenge", "चुनौती", "का बनवली"]):
        ch_title = challenge.get("title") or f"Addressing {category} in {locality}"
        ch_status = challenge.get("challenge_status", "DRAFT")
        if is_hindi:
            resp_text = f"यह चुनौती ('{ch_title}') इसलिए बनाई गई क्योंकि क्लस्टर के साक्ष्य और नागरिक रिपोर्ट एक सतत समस्या दर्शाते हैं। वर्तमान में इसकी स्थिति: {ch_status} है।"
        elif is_marathi:
            resp_text = f"हे आव्हान ('{ch_title}') तयार केले गेले कारण पुराव्यांवरून ही एक गंभीर नागरी समस्या असल्याचे स्पष्ट होते. सद्यस्थिती: {ch_status}."
        else:
            resp_text = f"This challenge ('{ch_title}') was structured from verified cluster evidence and citizen testimony. Its current lifecycle status is: {ch_status}."
        related_actions = ["Explain Challenge", "What Happens Next?"]

    # Default fallback response
    else:
        if is_hindi:
            resp_text = f"नमस्ते! मैं RAKA AI सहायक हूँ। मैं आपकी रिपोर्ट ({category} - {locality}), क्लस्टर डेटा, और समाधान चुनौती को समझने में आपकी मदद कर सकता हूँ। आप क्या जानना चाहते हैं?"
        elif is_marathi:
            resp_text = f"नमस्कार! मी RAKA AI सहाय्यक आहे. मी आपल्या समस्येचे वर्गीकरण ({category}), Cluster माहिती आणि आव्हान समजून घेण्यात मदत करू शकतो."
        else:
            resp_text = f"Hello! I am RAKA AI Assistant. I can help explain your problem analysis ({category} in {locality}), related community clusters, stakeholder routing, and innovation challenges. What would you like to know?"
        related_actions = ["Explain My Analysis", "Show Related Problems", "Explain Stakeholder Match", "What Happens Next?"]

    return ChatResponse(
        message=resp_text,
        language=lang,
        conversationId=str(uuid.uuid4()),
        contextType=context_type,
        sources=sources[:3],
        relatedActions=related_actions
    )


def process_chat_message(req: ChatRequest) -> ChatResponse:
    """
    Main Step 5 Chat Handler:
    1. Creates or loads conversation in database.
    2. Gathers verified RAKA context (Problem, Cluster, Challenge).
    3. Determines priority language.
    4. Calls Gemini 2.5 Flash or Heuristic Q&A Engine.
    5. Saves messages in `chat_messages` table.
    6. Returns `ChatResponse`.
    """
    # 1. Determine conversation ID
    conv_id = db.create_or_get_chat_conversation(
        conversation_id=req.conversationId,
        problem_id=req.problemId,
        cluster_id=req.clusterId,
        challenge_id=req.challengeId,
        preferred_language=req.language or "en"
    )

    # 2. Gather verified RAKA context
    context_type, ctx, available_sources = gather_chat_context(
        problem_id=req.problemId,
        cluster_id=req.clusterId,
        challenge_id=req.challengeId
    )

    # 3. Detect and resolve language
    detected_lang, _ = detect_language_simple(req.message)
    effective_lang = req.language or "en"
    if detected_lang != "English" and (not req.language or req.language == "en"):
        effective_lang = detected_lang

    # 4. Save user message to database
    db.save_chat_message(
        conversation_id=conv_id,
        role="USER",
        message=req.message,
        language=effective_lang
    )

    # 5. Fetch recent chat history
    history = db.get_chat_messages(conv_id, limit=6)
    history_fmt = [f"{m['role']}: {m['message']}" for m in history[:-1]]

    # 6. Call Gemini 2.5 Flash or Fallback
    api_key = os.getenv("GEMINI_API_KEY")
    chat_resp: Optional[ChatResponse] = None

    if api_key:
        try:
            from google import genai
            from google.genai import types

            client = genai.Client(api_key=api_key)
            prompt = f"""
            {SYSTEM_INSTRUCTION}

            USER'S LANGUAGE PREFERENCE: {effective_lang}
            ACTIVE CONTEXT TYPE: {context_type}
            VERIFIED RAKA DATABASE CONTEXT:
            {json.dumps(ctx, default=str)}

            RECENT CONVERSATION HISTORY:
            {json.dumps(history_fmt)}

            CURRENT USER MESSAGE: \"\"\"{req.message}\"\"\"

            Respond concisely and accurately in {effective_lang}.
            """

            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=[prompt],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json"
                )
            )

            raw_json = response.text or "{}"
            parsed = json.loads(raw_json)
            
            resp_sources = []
            for s in parsed.get("sources", []):
                resp_sources.append(ChatSource(
                    type=s.get("type", "AI_ANALYSIS"),
                    field=s.get("field", "general"),
                    snippet=s.get("snippet")
                ))
            if not resp_sources:
                resp_sources = available_sources[:3]

            chat_resp = ChatResponse(
                message=parsed.get("message", "Here is what RAKA found."),
                language=effective_lang,
                conversationId=conv_id,
                contextType=context_type,
                sources=resp_sources,
                relatedActions=parsed.get("relatedActions", ["Explain My Analysis", "What Happens Next?"])
            )
        except Exception as e:
            print(f"[ChatService] Gemini chat call failed: {e}. Using heuristic context engine.")
            chat_resp = None

    if not chat_resp:
        chat_resp = heuristic_chat_response(
            message=req.message,
            context_type=context_type,
            context=ctx,
            lang=effective_lang,
            sources=available_sources
        )
        chat_resp.conversationId = conv_id

    # 7. Save assistant message to database
    db.save_chat_message(
        conversation_id=conv_id,
        role="ASSISTANT",
        message=chat_resp.message,
        language=chat_resp.language,
        sources=[s.model_dump() for s in chat_resp.sources]
    )

    return chat_resp


def process_voice_chat(
    audio_path: Path,
    problem_id: Optional[str] = None,
    cluster_id: Optional[str] = None,
    challenge_id: Optional[str] = None,
    language: Optional[str] = "Hindi",
    conversation_id: Optional[str] = None
) -> Tuple[str, ChatResponse]:
    """
    Step 5 Voice Chat Handler:
    1. Transcribes audio with speech-to-text.
    2. Identifies spoken language.
    3. Feeds transcribed text to `process_chat_message`.
    4. Returns: (transcription, ChatResponse)
    """
    transcription, detected_lang, confidence = transcribe_audio_file(
        audio_path=audio_path,
        preferred_language=language
    )

    effective_msg = transcription or "Hello RAKA, please explain this."
    req = ChatRequest(
        message=effective_msg,
        problemId=problem_id,
        clusterId=cluster_id,
        challengeId=challenge_id,
        language=detected_lang or language,
        conversationId=conversation_id
    )

    resp = process_chat_message(req)
    return transcription, resp
